#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xBE86EBB415104FDF (dan@berrange.com)
#
Name     : libvirt-glib
Version  : 1.0.0
Release  : 8
URL      : https://libvirt.org/sources/glib/libvirt-glib-1.0.0.tar.gz
Source0  : https://libvirt.org/sources/glib/libvirt-glib-1.0.0.tar.gz
Source99 : https://libvirt.org/sources/glib/libvirt-glib-1.0.0.tar.gz.asc
Summary  : libvirt glib integration for events
Group    : Development/Tools
License  : LGPL-2.1 LGPL-2.1+
Requires: libvirt-glib-lib
Requires: libvirt-glib-doc
Requires: libvirt-glib-locales
Requires: libvirt-glib-data
BuildRequires : docbook-xml
BuildRequires : gobject-introspection-dev
BuildRequires : gtk-doc
BuildRequires : gtk-doc-dev
BuildRequires : intltool
BuildRequires : libxslt-bin
BuildRequires : pkgconfig(gio-2.0)
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(gobject-2.0)
BuildRequires : pkgconfig(gthread-2.0)
BuildRequires : pkgconfig(libvirt)
BuildRequires : pkgconfig(libxml-2.0)

%description
This package provides integration between libvirt and the glib
event loop.

%package data
Summary: data components for the libvirt-glib package.
Group: Data

%description data
data components for the libvirt-glib package.


%package dev
Summary: dev components for the libvirt-glib package.
Group: Development
Requires: libvirt-glib-lib
Requires: libvirt-glib-data
Provides: libvirt-glib-devel

%description dev
dev components for the libvirt-glib package.


%package doc
Summary: doc components for the libvirt-glib package.
Group: Documentation

%description doc
doc components for the libvirt-glib package.


%package lib
Summary: lib components for the libvirt-glib package.
Group: Libraries
Requires: libvirt-glib-data

%description lib
lib components for the libvirt-glib package.


%package locales
Summary: locales components for the libvirt-glib package.
Group: Default

%description locales
locales components for the libvirt-glib package.


%prep
%setup -q -n libvirt-glib-1.0.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1493801722
%configure --disable-static
make V=1  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1493801722
rm -rf %{buildroot}
%make_install
%find_lang libvirt-glib

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/lib64/girepository-1.0/LibvirtGConfig-1.0.typelib
/usr/lib64/girepository-1.0/LibvirtGLib-1.0.typelib
/usr/lib64/girepository-1.0/LibvirtGObject-1.0.typelib
/usr/share/gir-1.0/*.gir

%files dev
%defattr(-,root,root,-)
/usr/include/libvirt-gconfig-1.0/libvirt-gconfig/libvirt-gconfig-capabilities-cpu-feature.h
/usr/include/libvirt-gconfig-1.0/libvirt-gconfig/libvirt-gconfig-capabilities-cpu-model.h
/usr/include/libvirt-gconfig-1.0/libvirt-gconfig/libvirt-gconfig-capabilities-cpu-topology.h
/usr/include/libvirt-gconfig-1.0/libvirt-gconfig/libvirt-gconfig-capabilities-cpu.h
/usr/include/libvirt-gconfig-1.0/libvirt-gconfig/libvirt-gconfig-capabilities-guest-arch.h
/usr/include/libvirt-gconfig-1.0/libvirt-gconfig/libvirt-gconfig-capabilities-guest-domain.h
/usr/include/libvirt-gconfig-1.0/libvirt-gconfig/libvirt-gconfig-capabilities-guest-feature.h
/usr/include/libvirt-gconfig-1.0/libvirt-gconfig/libvirt-gconfig-capabilities-guest.h
/usr/include/libvirt-gconfig-1.0/libvirt-gconfig/libvirt-gconfig-capabilities-host-secmodel.h
/usr/include/libvirt-gconfig-1.0/libvirt-gconfig/libvirt-gconfig-capabilities-host.h
/usr/include/libvirt-gconfig-1.0/libvirt-gconfig/libvirt-gconfig-capabilities.h
/usr/include/libvirt-gconfig-1.0/libvirt-gconfig/libvirt-gconfig-domain-address-pci.h
/usr/include/libvirt-gconfig-1.0/libvirt-gconfig/libvirt-gconfig-domain-address-usb.h
/usr/include/libvirt-gconfig-1.0/libvirt-gconfig/libvirt-gconfig-domain-address.h
/usr/include/libvirt-gconfig-1.0/libvirt-gconfig/libvirt-gconfig-domain-channel.h
/usr/include/libvirt-gconfig-1.0/libvirt-gconfig/libvirt-gconfig-domain-chardev-source-pty.h
/usr/include/libvirt-gconfig-1.0/libvirt-gconfig/libvirt-gconfig-domain-chardev-source-spiceport.h
/usr/include/libvirt-gconfig-1.0/libvirt-gconfig/libvirt-gconfig-domain-chardev-source-spicevmc.h
/usr/include/libvirt-gconfig-1.0/libvirt-gconfig/libvirt-gconfig-domain-chardev-source-unix.h
/usr/include/libvirt-gconfig-1.0/libvirt-gconfig/libvirt-gconfig-domain-chardev-source.h
/usr/include/libvirt-gconfig-1.0/libvirt-gconfig/libvirt-gconfig-domain-chardev.h
/usr/include/libvirt-gconfig-1.0/libvirt-gconfig/libvirt-gconfig-domain-clock.h
/usr/include/libvirt-gconfig-1.0/libvirt-gconfig/libvirt-gconfig-domain-console.h
/usr/include/libvirt-gconfig-1.0/libvirt-gconfig/libvirt-gconfig-domain-controller-usb.h
/usr/include/libvirt-gconfig-1.0/libvirt-gconfig/libvirt-gconfig-domain-controller.h
/usr/include/libvirt-gconfig-1.0/libvirt-gconfig/libvirt-gconfig-domain-cpu-feature.h
/usr/include/libvirt-gconfig-1.0/libvirt-gconfig/libvirt-gconfig-domain-cpu-model.h
/usr/include/libvirt-gconfig-1.0/libvirt-gconfig/libvirt-gconfig-domain-cpu.h
/usr/include/libvirt-gconfig-1.0/libvirt-gconfig/libvirt-gconfig-domain-device.h
/usr/include/libvirt-gconfig-1.0/libvirt-gconfig/libvirt-gconfig-domain-disk-driver.h
/usr/include/libvirt-gconfig-1.0/libvirt-gconfig/libvirt-gconfig-domain-disk.h
/usr/include/libvirt-gconfig-1.0/libvirt-gconfig/libvirt-gconfig-domain-filesys.h
/usr/include/libvirt-gconfig-1.0/libvirt-gconfig/libvirt-gconfig-domain-graphics-desktop.h
/usr/include/libvirt-gconfig-1.0/libvirt-gconfig/libvirt-gconfig-domain-graphics-rdp.h
/usr/include/libvirt-gconfig-1.0/libvirt-gconfig/libvirt-gconfig-domain-graphics-sdl.h
/usr/include/libvirt-gconfig-1.0/libvirt-gconfig/libvirt-gconfig-domain-graphics-spice.h
/usr/include/libvirt-gconfig-1.0/libvirt-gconfig/libvirt-gconfig-domain-graphics-vnc.h
/usr/include/libvirt-gconfig-1.0/libvirt-gconfig/libvirt-gconfig-domain-graphics.h
/usr/include/libvirt-gconfig-1.0/libvirt-gconfig/libvirt-gconfig-domain-hostdev-pci.h
/usr/include/libvirt-gconfig-1.0/libvirt-gconfig/libvirt-gconfig-domain-hostdev.h
/usr/include/libvirt-gconfig-1.0/libvirt-gconfig/libvirt-gconfig-domain-input.h
/usr/include/libvirt-gconfig-1.0/libvirt-gconfig/libvirt-gconfig-domain-interface-bridge.h
/usr/include/libvirt-gconfig-1.0/libvirt-gconfig/libvirt-gconfig-domain-interface-filterref-parameter.h
/usr/include/libvirt-gconfig-1.0/libvirt-gconfig/libvirt-gconfig-domain-interface-filterref.h
/usr/include/libvirt-gconfig-1.0/libvirt-gconfig/libvirt-gconfig-domain-interface-network.h
/usr/include/libvirt-gconfig-1.0/libvirt-gconfig/libvirt-gconfig-domain-interface-user.h
/usr/include/libvirt-gconfig-1.0/libvirt-gconfig/libvirt-gconfig-domain-interface.h
/usr/include/libvirt-gconfig-1.0/libvirt-gconfig/libvirt-gconfig-domain-memballoon.h
/usr/include/libvirt-gconfig-1.0/libvirt-gconfig/libvirt-gconfig-domain-os.h
/usr/include/libvirt-gconfig-1.0/libvirt-gconfig/libvirt-gconfig-domain-parallel.h
/usr/include/libvirt-gconfig-1.0/libvirt-gconfig/libvirt-gconfig-domain-power-management.h
/usr/include/libvirt-gconfig-1.0/libvirt-gconfig/libvirt-gconfig-domain-redirdev.h
/usr/include/libvirt-gconfig-1.0/libvirt-gconfig/libvirt-gconfig-domain-seclabel.h
/usr/include/libvirt-gconfig-1.0/libvirt-gconfig/libvirt-gconfig-domain-serial.h
/usr/include/libvirt-gconfig-1.0/libvirt-gconfig/libvirt-gconfig-domain-smartcard-host-certificates.h
/usr/include/libvirt-gconfig-1.0/libvirt-gconfig/libvirt-gconfig-domain-smartcard-host.h
/usr/include/libvirt-gconfig-1.0/libvirt-gconfig/libvirt-gconfig-domain-smartcard-passthrough.h
/usr/include/libvirt-gconfig-1.0/libvirt-gconfig/libvirt-gconfig-domain-smartcard.h
/usr/include/libvirt-gconfig-1.0/libvirt-gconfig/libvirt-gconfig-domain-snapshot-disk.h
/usr/include/libvirt-gconfig-1.0/libvirt-gconfig/libvirt-gconfig-domain-snapshot.h
/usr/include/libvirt-gconfig-1.0/libvirt-gconfig/libvirt-gconfig-domain-sound.h
/usr/include/libvirt-gconfig-1.0/libvirt-gconfig/libvirt-gconfig-domain-timer-hpet.h
/usr/include/libvirt-gconfig-1.0/libvirt-gconfig/libvirt-gconfig-domain-timer-pit.h
/usr/include/libvirt-gconfig-1.0/libvirt-gconfig/libvirt-gconfig-domain-timer-rtc.h
/usr/include/libvirt-gconfig-1.0/libvirt-gconfig/libvirt-gconfig-domain-timer.h
/usr/include/libvirt-gconfig-1.0/libvirt-gconfig/libvirt-gconfig-domain-video.h
/usr/include/libvirt-gconfig-1.0/libvirt-gconfig/libvirt-gconfig-domain.h
/usr/include/libvirt-gconfig-1.0/libvirt-gconfig/libvirt-gconfig-enum-types.h
/usr/include/libvirt-gconfig-1.0/libvirt-gconfig/libvirt-gconfig-helpers.h
/usr/include/libvirt-gconfig-1.0/libvirt-gconfig/libvirt-gconfig-interface.h
/usr/include/libvirt-gconfig-1.0/libvirt-gconfig/libvirt-gconfig-main.h
/usr/include/libvirt-gconfig-1.0/libvirt-gconfig/libvirt-gconfig-network-filter.h
/usr/include/libvirt-gconfig-1.0/libvirt-gconfig/libvirt-gconfig-network.h
/usr/include/libvirt-gconfig-1.0/libvirt-gconfig/libvirt-gconfig-node-device.h
/usr/include/libvirt-gconfig-1.0/libvirt-gconfig/libvirt-gconfig-object.h
/usr/include/libvirt-gconfig-1.0/libvirt-gconfig/libvirt-gconfig-secret.h
/usr/include/libvirt-gconfig-1.0/libvirt-gconfig/libvirt-gconfig-storage-permissions.h
/usr/include/libvirt-gconfig-1.0/libvirt-gconfig/libvirt-gconfig-storage-pool-source.h
/usr/include/libvirt-gconfig-1.0/libvirt-gconfig/libvirt-gconfig-storage-pool-target.h
/usr/include/libvirt-gconfig-1.0/libvirt-gconfig/libvirt-gconfig-storage-pool.h
/usr/include/libvirt-gconfig-1.0/libvirt-gconfig/libvirt-gconfig-storage-vol-backing-store.h
/usr/include/libvirt-gconfig-1.0/libvirt-gconfig/libvirt-gconfig-storage-vol-target.h
/usr/include/libvirt-gconfig-1.0/libvirt-gconfig/libvirt-gconfig-storage-vol.h
/usr/include/libvirt-gconfig-1.0/libvirt-gconfig/libvirt-gconfig.h
/usr/include/libvirt-glib-1.0/libvirt-glib/libvirt-glib-error.h
/usr/include/libvirt-glib-1.0/libvirt-glib/libvirt-glib-event.h
/usr/include/libvirt-glib-1.0/libvirt-glib/libvirt-glib-main.h
/usr/include/libvirt-glib-1.0/libvirt-glib/libvirt-glib.h
/usr/include/libvirt-gobject-1.0/libvirt-gobject/libvirt-gobject-connection.h
/usr/include/libvirt-gobject-1.0/libvirt-gobject/libvirt-gobject-domain-device.h
/usr/include/libvirt-gobject-1.0/libvirt-gobject/libvirt-gobject-domain-disk.h
/usr/include/libvirt-gobject-1.0/libvirt-gobject/libvirt-gobject-domain-interface.h
/usr/include/libvirt-gobject-1.0/libvirt-gobject/libvirt-gobject-domain-snapshot.h
/usr/include/libvirt-gobject-1.0/libvirt-gobject/libvirt-gobject-domain.h
/usr/include/libvirt-gobject-1.0/libvirt-gobject/libvirt-gobject-enums.h
/usr/include/libvirt-gobject-1.0/libvirt-gobject/libvirt-gobject-interface.h
/usr/include/libvirt-gobject-1.0/libvirt-gobject/libvirt-gobject-main.h
/usr/include/libvirt-gobject-1.0/libvirt-gobject/libvirt-gobject-manager.h
/usr/include/libvirt-gobject-1.0/libvirt-gobject/libvirt-gobject-network-dhcp-lease.h
/usr/include/libvirt-gobject-1.0/libvirt-gobject/libvirt-gobject-network-filter.h
/usr/include/libvirt-gobject-1.0/libvirt-gobject/libvirt-gobject-network.h
/usr/include/libvirt-gobject-1.0/libvirt-gobject/libvirt-gobject-node-device.h
/usr/include/libvirt-gobject-1.0/libvirt-gobject/libvirt-gobject-secret.h
/usr/include/libvirt-gobject-1.0/libvirt-gobject/libvirt-gobject-storage-pool.h
/usr/include/libvirt-gobject-1.0/libvirt-gobject/libvirt-gobject-storage-vol.h
/usr/include/libvirt-gobject-1.0/libvirt-gobject/libvirt-gobject-stream.h
/usr/include/libvirt-gobject-1.0/libvirt-gobject/libvirt-gobject.h
/usr/lib64/libvirt-gconfig-1.0.so
/usr/lib64/libvirt-glib-1.0.so
/usr/lib64/libvirt-gobject-1.0.so
/usr/lib64/pkgconfig/libvirt-gconfig-1.0.pc
/usr/lib64/pkgconfig/libvirt-glib-1.0.pc
/usr/lib64/pkgconfig/libvirt-gobject-1.0.pc

%files doc
%defattr(-,root,root,-)
/usr/share/gtk-doc/html/Libvirt-gconfig/GVirConfigCapabilities.html
/usr/share/gtk-doc/html/Libvirt-gconfig/GVirConfigDomain.html
/usr/share/gtk-doc/html/Libvirt-gconfig/GVirConfigDomainSnapshot.html
/usr/share/gtk-doc/html/Libvirt-gconfig/GVirConfigInterface.html
/usr/share/gtk-doc/html/Libvirt-gconfig/GVirConfigNetwork.html
/usr/share/gtk-doc/html/Libvirt-gconfig/GVirConfigNetworkFilter.html
/usr/share/gtk-doc/html/Libvirt-gconfig/GVirConfigNodeDevice.html
/usr/share/gtk-doc/html/Libvirt-gconfig/GVirConfigObject.html
/usr/share/gtk-doc/html/Libvirt-gconfig/GVirConfigSecret.html
/usr/share/gtk-doc/html/Libvirt-gconfig/GVirConfigStoragePool.html
/usr/share/gtk-doc/html/Libvirt-gconfig/GVirConfigStorageVol.html
/usr/share/gtk-doc/html/Libvirt-gconfig/Libvirt-gconfig.devhelp2
/usr/share/gtk-doc/html/Libvirt-gconfig/annotation-glossary.html
/usr/share/gtk-doc/html/Libvirt-gconfig/api-index-full.html
/usr/share/gtk-doc/html/Libvirt-gconfig/ch01.html
/usr/share/gtk-doc/html/Libvirt-gconfig/home.png
/usr/share/gtk-doc/html/Libvirt-gconfig/index.html
/usr/share/gtk-doc/html/Libvirt-gconfig/left-insensitive.png
/usr/share/gtk-doc/html/Libvirt-gconfig/left.png
/usr/share/gtk-doc/html/Libvirt-gconfig/object-tree.html
/usr/share/gtk-doc/html/Libvirt-gconfig/right-insensitive.png
/usr/share/gtk-doc/html/Libvirt-gconfig/right.png
/usr/share/gtk-doc/html/Libvirt-gconfig/style.css
/usr/share/gtk-doc/html/Libvirt-gconfig/up-insensitive.png
/usr/share/gtk-doc/html/Libvirt-gconfig/up.png
/usr/share/gtk-doc/html/Libvirt-glib/Libvirt-glib-Error-reporting.html
/usr/share/gtk-doc/html/Libvirt-glib/Libvirt-glib-Event-loop.html
/usr/share/gtk-doc/html/Libvirt-glib/Libvirt-glib-Library-initialization.html
/usr/share/gtk-doc/html/Libvirt-glib/Libvirt-glib.devhelp2
/usr/share/gtk-doc/html/Libvirt-glib/annotation-glossary.html
/usr/share/gtk-doc/html/Libvirt-glib/api-index-full.html
/usr/share/gtk-doc/html/Libvirt-glib/ch01.html
/usr/share/gtk-doc/html/Libvirt-glib/home.png
/usr/share/gtk-doc/html/Libvirt-glib/index.html
/usr/share/gtk-doc/html/Libvirt-glib/left-insensitive.png
/usr/share/gtk-doc/html/Libvirt-glib/left.png
/usr/share/gtk-doc/html/Libvirt-glib/object-tree.html
/usr/share/gtk-doc/html/Libvirt-glib/right-insensitive.png
/usr/share/gtk-doc/html/Libvirt-glib/right.png
/usr/share/gtk-doc/html/Libvirt-glib/style.css
/usr/share/gtk-doc/html/Libvirt-glib/up-insensitive.png
/usr/share/gtk-doc/html/Libvirt-glib/up.png
/usr/share/gtk-doc/html/Libvirt-gobject/GVirConnection.html
/usr/share/gtk-doc/html/Libvirt-gobject/GVirDomain.html
/usr/share/gtk-doc/html/Libvirt-gobject/GVirDomainSnapshot.html
/usr/share/gtk-doc/html/Libvirt-gobject/GVirInterface.html
/usr/share/gtk-doc/html/Libvirt-gobject/GVirManager.html
/usr/share/gtk-doc/html/Libvirt-gobject/GVirNetwork.html
/usr/share/gtk-doc/html/Libvirt-gobject/GVirNetworkFilter.html
/usr/share/gtk-doc/html/Libvirt-gobject/GVirNodeDevice.html
/usr/share/gtk-doc/html/Libvirt-gobject/GVirSecret.html
/usr/share/gtk-doc/html/Libvirt-gobject/GVirStoragePool.html
/usr/share/gtk-doc/html/Libvirt-gobject/GVirStorageVol.html
/usr/share/gtk-doc/html/Libvirt-gobject/GVirStream.html
/usr/share/gtk-doc/html/Libvirt-gobject/Libvirt-gobject.devhelp2
/usr/share/gtk-doc/html/Libvirt-gobject/annotation-glossary.html
/usr/share/gtk-doc/html/Libvirt-gobject/api-index-full.html
/usr/share/gtk-doc/html/Libvirt-gobject/ch01.html
/usr/share/gtk-doc/html/Libvirt-gobject/home.png
/usr/share/gtk-doc/html/Libvirt-gobject/index.html
/usr/share/gtk-doc/html/Libvirt-gobject/left-insensitive.png
/usr/share/gtk-doc/html/Libvirt-gobject/left.png
/usr/share/gtk-doc/html/Libvirt-gobject/object-tree.html
/usr/share/gtk-doc/html/Libvirt-gobject/right-insensitive.png
/usr/share/gtk-doc/html/Libvirt-gobject/right.png
/usr/share/gtk-doc/html/Libvirt-gobject/style.css
/usr/share/gtk-doc/html/Libvirt-gobject/up-insensitive.png
/usr/share/gtk-doc/html/Libvirt-gobject/up.png

%files lib
%defattr(-,root,root,-)
/usr/lib64/libvirt-gconfig-1.0.so.0
/usr/lib64/libvirt-gconfig-1.0.so.0.1000.0
/usr/lib64/libvirt-glib-1.0.so.0
/usr/lib64/libvirt-glib-1.0.so.0.1000.0
/usr/lib64/libvirt-gobject-1.0.so.0
/usr/lib64/libvirt-gobject-1.0.so.0.1000.0

%files locales -f libvirt-glib.lang
%defattr(-,root,root,-)

